#!/bin/bash

# Todo:
# • Add further airspaces when they are converted to new file name format

# Include airspaces (define here which airspaces should be included into output file)
# set variable to "true" for including or "false" for not including an airspace
# AllAirspaces="true" overrides all other settings and includes all airspaces into output (be carefull,
# this will result in a very big file!)
# For a finer selection of special airspaces, add or comment lines in SpecialAirspaces IF block

AllAirspaces="false"
SpecialAirspace="false"

AT_Austria="true"
CA_Canada="false"
CH_Switzerland="false"
CZ_Czechia="false"
DE_Germany="false"
FI_Finland="false"
GB_UnitedKingdom="false"
IT_Italy="false"
NL_Netherlands="false"
SK_Slovakia="false"

# Do all the program stuff, nothing to change anymore down below (except special airspaces)

clear
echo "Airspace combining script"
echo "V. Pippan (https://www.vpippan.at | webmaster@vpippan.at)"
echo "CC-BY-SA 2021"

AirspaceString=""
OutputFileNameString="airspace_"

if $SpecialAirspace || $AllAirspaces
then
  #AirspaceString+="../airspaces/special/airspace_special_.txt "
  #OutputFileNameString+="special_"
  #echo "Adding airspaces Special"
fi

if $AT_Austria || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_at_austria.txt "
  OutputFileNameString+="at_"
  echo "Adding airspace Austria"
fi
if $CA_Canada || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_ca_canada.txt "
  OutputFileNameString+="ca_"
  echo "Adding airspace Canada"
fi
if $CH_Switzerland || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_ch_switzerland.txt "
  OutputFileNameString+="ch_"
  echo "Adding airspace Switzerland"
fi
if $CZ_Czechia || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_cz_czechia.txt "
  OutputFileNameString+="cz_"
  echo "Adding airspace Czechia"
fi
if $DE_Germany || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_de_germany.txt "
  OutputFileNameString+="de_"
  echo "Adding airspace Germany"
fi
if $FI_Finland || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_fi_finland.txt "
  OutputFileNameString+="fi_"
  echo "Adding airspace Finland"
fi
if $GB_UnitedKingdom || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_gb_unitedkingdom.txt "
  OutputFileNameString+="gb_"
  echo "Adding airspace United Kingdom"
fi
if $IT_Italy || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_it_italy.txt "
  OutputFileNameString+="it_"
  echo "Adding airspace Italy"
fi
if $NL_Netherlands || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_nl_netherlands.txt "
  OutputFileNameString+="nl_"
  echo "Adding airspace Netherlands"
fi
if $SK_Slovakia || $AllAirspaces
then
  AirspaceString+="../airspaces/airspace_sk_slovakia.txt "
  OutputFileNameString+="sk_"
  echo "Adding airspace Slovakia"
fi
if $AllAirspaces
then
  OutputFileNameString="airspace_all_"
fi

# for testing (can be removed later)
#echo $AirspaceString
#echo $OutputFileNameString

# concatenate all files
cat $AirspaceString > ../$OutputFileNameString`date +%4Y%m%d`.txt
